// import { addDays, subDays } from 'date-fns'
// import { ItemDetail } from '../../../redux/item/index'

// export const fixtureAuctionItem: ItemDetail = {
//   itemId: '123',
//   type: 'nft',
//   tradeType: 'auction',
//   tokenId: 1000001,
//   name: 'test',
//   description: 'テストな作品です',
//   tokenURI: '#',
//   tokenURIHTTP: '',
//   imageURI: '',
//   imageURIHTTP: {
//     url: '',
//     mimeType: '',
//   },
//   authorAddress: '',
//   previews: [{ mimeType: '', url: '' }],
//   networkId: 1,
//   buyerAddress: null,
//   currentPrice: 1.32,
//   currentBidderAddress: '0xxxxx',
//   minBidPrice: 0.1,
//   minBidPercentage: 0.1,
//   startAt: new Date(),
//   endAt: addDays(new Date(), 10),
//   initialPrice: 1,
//   chainType: 'ethereum',
//   collectionId: 'xxxx',
//   mintContractAddress: '',
//   mintShopContractAddress: '',
//   createdBy: [],
//   yearCreated: '2011',
//   feeRatePermill: 10,
// }

// export const fixtureAuctionEnd: ItemDetail = {
//   itemId: '123',
//   type: 'nft',
//   tradeType: 'auction',
//   tokenId: 1000001,
//   name: 'test',
//   description: 'テストな作品です',
//   tokenURI: '#',
//   tokenURIHTTP: '',
//   imageURI: '',
//   imageURIHTTP: {
//     url: '',
//     mimeType: '',
//   },
//   authorAddress: '',
//   previews: [{ mimeType: '', url: '' }],
//   networkId: 1,
//   buyerAddress: null,
//   currentPrice: 1.32,
//   currentBidderAddress: '0xxxxx',
//   minBidPrice: 0.1,
//   minBidPercentage: 0.1,
//   startAt: new Date(),
//   endAt: subDays(new Date(), 10),
//   initialPrice: 1,
//   chainType: 'ethereum',
//   collectionId: 'xxxx',
//   mintContractAddress: '',
//   mintShopContractAddress: '',
//   createdBy: [],
//   yearCreated: '2011',
//   feeRatePermill: 10,
// }
