# This is a basic workflow to help you get started with Actions

name: check

# Controls when the action will run.
on: [pull_request]
  # Triggers the workflow on pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-src:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: npm i
        working-directory: ./
        run: npm ci
      - name: npm run lint:check
        working-directory: ./
        run: npm run lint:check
      - name: npm run type:check
        working-directory: ./
        run: npm run type:check
      - name: npm run format:check
        working-directory: ./
        run: npm run format:check

